name: med-exam-web

services:
  server:
    container_name: med-exam-web-server
    image: med-exam-web-server
    build:
      context: .
      target: production
    restart: on-failure:5
    depends_on:
      - db
    links:
      - db
    ports:
      - '8000:8000'
    volumes:
      - /var/log/med-web:/app/log
      - /var/lib/med-web/secrets:/app/secrets
      - /var/www/med-web/html/cache/images:/app/cache/images
      - /var/lib/med-web/dicoms:/app/data/dicoms
      - /var/lib/med-web/models:/app/models
    environment:
      PRODUCTION: true
      WEB_ROOT_PATH: /api
      DB_DIALECT: postgresql
      DB_DRIVER: asyncpg
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: main
      DATABASE_MAX_CONNECTIONS: 250 # 4 workers

  db:
    container_name: med-exam-web-db
    restart: on-failure:5
    image: postgres:16
    command: ["postgres", "-c", "max_connections=1000"]
    ports:
      - '54320:5432'
    volumes:
      - /var/lib/med-web/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
      POSTGRES_HOST_AUTH_METHOD: md5